AWSTemplateFormatVersion: 2010-09-09
Description: ---
#Metadata:

Parameters:

  DeadLetterAlarm:
    Default: false
    Type: String

  DeadLetterAlarmPeriod:
    Default: 300
    Type: String

  DeadLetterAlarmThreshold:
    Default: 0
    Type: String

  DelaySeconds:
    Default: 0
    Type: String

  KmsKey:
    Default: none
    Type: String

  MaxReceiveCount:
    Default: 3
    Type: String

  MessageRetentionPeriod:
    Default: 345600
    Type: String

  QueueName:
    Type: String

  ReceiveMessageWaitTimeSeconds:
    Default: 20
    Type: String

  SnsSubscriptionRawMessageDelivery:
    Default: true
    Type: String

  SnsSubscriptionTopicArn:
    Default: none
    Type: String

  VisibilityTimeout:
    Default: 30
    Type: String

#Mappings:

Conditions:

  HasDeadLetterAlarm: !Equals [ !Ref DeadLetterAlarm, true ]
  HasKmsKey: !Not [ !Equals [ !Ref KmsKey, none ] ]
  HasSnsSubscription: !Not [ !Equals [ !Ref SnsSubscriptionTopicArn, none ] ]

Resources:

  DeadLetterAlarmTopic:
    Condition: HasDeadLetterAlarm
    Type: AWS::SNS::Topic
    Properties:
      KmsMasterKeyId: !If [ HasKmsKey, !Ref KmsKey, 'AWS::NoValue' ]
      TopicName: !Sub ${QueueName}-dlq-alarm-topic

  DeadLetterCloudWatchAlarm:
    Condition: HasDeadLetterAlarm
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmActions:
        - !Ref DeadLetterAlarmTopic
      ComparisonOperator: GreaterThanThreshold
      Dimensions:
        - Name: QueueName
          Value: !GetAtt DeadLetterQueue.QueueName
      EvaluationPeriods: 1
      MetricName: ApproximateNumberOfMessagesVisible
      Namespace: 'AWS/SQS'
      Period: !Ref DeadLetterAlarmPeriod
      Statistic: Sum
      Threshold: !Ref DeadLetterAlarmThreshold

  DeadLetterQueue:
    Type: AWS::SQS::Queue
    Properties:
#      ContentBasedDeduplication: Boolean
      DelaySeconds: !Ref DelaySeconds
      KmsMasterKeyId: !If [ HasKmsKey, !Ref KmsKey, 'AWS::NoValue' ]
      MessageRetentionPeriod: !Ref MessageRetentionPeriod
      QueueName: !Sub ${QueueName}-dlq
      ReceiveMessageWaitTimeSeconds: !Ref ReceiveMessageWaitTimeSeconds
      VisibilityTimeout: !Ref VisibilityTimeout

  Queue:
    Type: AWS::SQS::Queue
    Properties:
#      ContentBasedDeduplication: Boolean
      DelaySeconds: !Ref DelaySeconds
      KmsMasterKeyId: !If [ HasKmsKey, !Ref KmsKey, 'AWS::NoValue' ]
      MessageRetentionPeriod: !Ref MessageRetentionPeriod
      QueueName: !Ref QueueName
      ReceiveMessageWaitTimeSeconds: !Ref ReceiveMessageWaitTimeSeconds
      RedrivePolicy:
        deadLetterTargetArn: !GetAtt DeadLetterQueue.Arn
        maxReceiveCount: !Ref MaxReceiveCount
      VisibilityTimeout: !Ref VisibilityTimeout

  SnsSubscription:
    Condition: HasSnsSubscription
    Type: AWS::SNS::Subscription
    Properties:
      Endpoint: !GetAtt Queue.Arn
      Protocol: sqs
      RawMessageDelivery: !Ref SnsSubscriptionRawMessageDelivery
      TopicArn: !Ref SnsSubscriptionTopicArn

Outputs:

  DeadLetterQueueArn:
    Value: !GetAtt DeadLetterQueue.Arn

  DeadLetterAlarmTopicArn:
    Value: !Ref DeadLetterAlarmTopic

  QueueArn:
    Value: !GetAtt Queue.Arn
