AWSTemplateFormatVersion: 2010-09-09
Description: ---

Parameters:

  ClusterName:
    Type: String

  DBClusterIdentifier:
    Default: none
    Type: String

  InstanceClass:
    Type: String

  Region:
    Default: us-east-1
    Type: String

  SecurityGroup:
    Type: String

  Sequence:
    Default: 1
    Type: String

  Stage:
    Type: String

#Conditions:

Resources:

  DatabaseInstance:
    Type: AWS::RDS::DBInstance
    Properties:
      DBClusterIdentifier: !Ref DBClusterIdentifier
      DBInstanceClass: !Ref InstanceClass
      DBInstanceIdentifier: !Sub ${ClusterName}-${Stage}-aurora-instance-${Sequence}
      DBParameterGroupName: !Ref ParameterGroup

  ParameterGroup:
    Type: AWS::RDS::DBParameterGroup
    Properties:
      Description: DBParameterGroup
      Family: aurora-mysql5.7
      Parameters:
        slow_query_log: 1

#Outputs:
