AWSTemplateFormatVersion: 2010-09-09
Description: ---

Parameters:

  ClusterName:
    Type: String

  DatabaseName:
    Default: none
    Type: String

  DBClusterIdentifier:
    Default: none
    Type: String

  InstanceClass:
    Type: String

  Region:
    Default: us-east-1
    Type: String

  SecurityGroup:
    Type: String

  Sequence:
    Default: 1
    Type: String

  Stage:
    Type: String

Conditions:

  HasCluster: !Not [ !Equals [ !Ref DBClusterIdentifier, none ] ]
  HasDatabaseName: !Not [ !Equals [ !Ref DatabaseName, none ] ]

Resources:

  DatabaseInstance:
    Type: AWS::RDS::DBInstance
    Properties:
      AvailabilityZone: !Sub ${Region}-1a
      DBClusterIdentifier: !If [ HasCluster, !Ref DBClusterIdentifier, 'AWS::NoValue' ]
      DBInstanceClass: !Ref InstanceClass
      DBInstanceIdentifier: !Sub ${ClusterName}-${Stage}-aurora-instance-${Sequence}
      DBName: !If [ HasDatabaseName, !Ref DatabaseName, 'AWS::NoValue' ]
      DBParameterGroupName: !Ref ParameterGroup
      DBSecurityGroups:
        - !Ref SecurityGroup
      Engine: aurora-mysql
      EngineVersion: 5.7.mysql_aurora.2.07.1
      MasterUsername: root
      MasterUserPassword: test1234
      VPCSecurityGroups:
        - SecurityGroup

  ParameterGroup:
    Type: AWS::RDS::DBParameterGroup
    Properties:
      Description: DBParameterGroup
      Family: aurora-mysql5.7
      Parameters:
        slow_query_log: 1

#Outputs:
