AWSTemplateFormatVersion: 2010-09-09
Description: ---

Parameters:

  ClusterName:
    Type: String

  Sequence:
    Default: 1
    Type: String

  Stage:
    Type: String

  SubnetIds:
    Type: CommaDelimitedList

  VpcCidr:
    Type: String

#Conditions:

Resources:

  CloudWatchLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/rds/cluster/${RdsCluster}/slowquery
      RetentionInDays: 3

  RdsClusterParameterGroup:
    Type: AWS::RDS::DBClusterParameterGroup
    Properties:
      Description: RdsClusterParameterGroup
      Family: aurora-mysql5.7
      Parameters:
        slow_query_log: 1

  RdsCluster:
    Type: AWS::RDS::DBCluster
    Properties:
      DBClusterIdentifier: !Sub ${ClusterName}-${Stage}-aurora-cluster-${Sequence}
      DBClusterParameterGroupName: !Ref RdsClusterParameterGroup
      DBSubnetGroupName: !Ref SubnetGroup
      EnableCloudwatchLogsExports:
        - slowquery
      Engine: aurora-mysql
      MasterUsername: root
      MasterUserPassword: test1234

  SecurityGroup:
    Type: AWS::RDS::DBSecurityGroup
    Properties:
      DBSecurityGroupIngress:
        - CIDRIP: !Ref VpcCidr
      GroupDescription: SecurityGroup

  SubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: SubnetGroup
      SubnetIds: !Ref SubnetIds

Outputs:

  DBClusterIdentifier:
    Value: !Ref RdsCluster

  SecurityGroup:
    Value: !Ref SecurityGroup
