AWSTemplateFormatVersion: 2010-09-09
Description: ---

Parameters:

  ClusterName:
    Type: String

  InstanceClass:
    Default: db.t3.small
    Type: String

  SecurityGroup:
    Type: String

  StackUrl:
    Type: String

  Stage:
    Type: String

  SubnetIds:
    Type: String

  VpcCidr:
    Type: String

#Conditions:

Resources:

  RdsAuroraMySqlClusterSubStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        ClusterName: !Ref ClusterName
        Stage: !Ref Stage
        SubnetIds: !Ref SubnetIds
        VpcCidr: !Ref VpcCidr
      TemplateURL: !Sub ${StackUrl}/rds/aurora-mysql-cluster.yaml

  RdsAuroraMySqlInstance1:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        DBClusterIdentifier: !GetAtt RdsAuroraMySqlClusterSubStack.Outputs.DBClusterIdentifier
        InstanceClass: !Ref InstanceClass
        Name: 1
        SecurityGroup: !Ref SecurityGroup
        Sequence: 1
        Stage: !Ref Stage
      TemplateURL: !Sub ${StackUrl}/rds/aurora-mysql-instance.yaml

#Outputs:
