AWSTemplateFormatVersion: 2010-09-09
Description: ---

Parameters:

  ClusterName:
    Type: String

  StackUrl:
    Type: String

  Stage:
    Type: String

  SubnetIds:
    Type: List<AWS::EC2::Subnet::Id>

  VpcId:
    Type: String

#Conditions:

Resources:

  RdsAuroraMysqlClusterSubStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        ClusterName: !Ref ClusterName
        Stage: !Ref Stage
        VpcId: !Ref VpcId
      TemplateURL: !Sub ${StackUrl}/rds/aurora-mysql-cluster.yaml

#Outputs:
