AWSTemplateFormatVersion: 2010-09-09
Description: ---
#Metadata:

Parameters:

  BucketName:
    Type: String

  SnsSubscriptionTopicArn:
    Default: none
    Type: String

#Mappings:

Conditions:

  HasSnsSubscription: !Not [ !Equals [ !Ref SnsSubscriptionTopicArn, none ] ]

Resources:

  Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub ${AWS::AccountId}-${BucketName}
      NotificationConfiguration:
        !If
        - HasSnsSubscription
        - TopicConfigurations:
            - Event: s3:ObjectCreated:Put
              Topic: !Ref SnsSubscriptionTopicArn
        - !Ref 'AWS::NoValue'

  SnsTopicPolicy:
    Condition: HasSnsSubscription
    Type: AWS::SNS::TopicPolicy
    Properties:
      Topics:
        - !Ref SnsSubscriptionTopicArn
      PolicyDocument:
        Id: SNSTopicPolicy
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              AWS:
                - '*'
            Action:
              - sns:Publish
            Resource:
              - !Ref SnsSubscriptionTopicArn
            Condition:
              ArnLike:
                aws:SourceArn: !Sub 'arn:aws:s3:::${Bucket}'

#Outputs:
