#AWSTemplateFormatVersion: 2010-09-09
#Description: ---
#Metadata:

Parameters:

  AmiId:
    Type: String

  InstanceType:
    Default: t3.micro
    Type: String

  LoadBalancerArn:
    Default: none
    Type: String

  PrivateSubnetIdList:
    Type: String

  PublicSubnetIdList:
    Default: ''
    Type: String

  Sequence:
    Default: 1
    Type: String

  Stage:
    Type: String

  StackUrl:
    Type: String

  SubnetA:
    Type: String

  SubnetB:
    Type: String

  VpcCidr:
    Type: String

  VpcId:
    Type: String

#Mappings:

Conditions:

  CreateLoadBalancer: !Equals [ !Ref LoadBalancerArn, none ]

Resources:

  EfsFileSystem:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        SubnetA: !Ref SubnetA
        SubnetB: !Ref SubnetB
        VpcCidr: !Ref VpcCidr
        VpcId: !Ref VpcId
      TemplateURL: !Sub ${StackUrl}/efs/simple.yaml

  LoadBalancer:
    Condition: CreateLoadBalancer
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      IpAddressType: ipv4
      Name: !Sub jenkins-master-${Sequence}-${Stage}-app-lb
      Scheme: internet-facing
      Subnets: !Split [ ',', !Ref PublicSubnetIdList ]
      Type: application

  JenkinsApplicationSubStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        AmiId: !Ref AmiId
        ApplicationName: !Sub jenkins-master-${Sequence}
        CreateElasticFileSystem: true
        InstanceType: !Ref InstanceType
        LoadBalancerArn: !If [ CreateLoadBalancer, !Ref LoadBalancer, !Ref LoadBalancerArn ]
        PrivateSubnetIdList: !Ref PrivateSubnetIdList
        Stage: !Ref Stage
        SubnetA: !Ref SubnetA
        SubnetB: !Ref SubnetB
        UserData:
          'Fn::Join':
            - '\n'
            - 'mkdir /var/lib/jenkins && chown -R jenkins:jenkins /var/lib/jenkins && echo "${EfsFileSystemStack.Outputs.EfsFileSystemId}:/ /var/lib/jenkins efs tls,_netdev 0 0" >> /etc/fstab && mount -a -t efs'
        VpcCidr: !Ref VpcCidr
        VpcId: !Ref VpcId
      TemplateURL: !Sub ${StackUrl}/ec2/application.yaml

#Outputs:
