AWSTemplateFormatVersion: 2010-09-09
Description: ---
#Metadata:

Parameters:

  BastionAmiId:
    Default: none
    Type: String

  BastionInstanceType:
    Default: t3.nano
    Type: String

  BastionKeyName:
    Default: none
    Type: String

  CidrClassB:
    Type: String

  Domain:
    Default: none
    Type: String

  Name:
    Type: String

  NatAmiId:
    Type: String

  NatKeyName:
    Default: none
    Type: String

  NatInstanceType:
    Default: t3.micro
    Type: String

  StackUrl:
    Type: String

  Stage:
    Default: dev
    Type: String

#Mappings:

Conditions:

  HasBastion: !Not [ !Equals [ !Ref BastionAmiId, none ] ]
  HasBastionKeyName: !Not [ !Equals [ !Ref BastionKeyName, none ] ]
  HasDomain: !Not [ !Equals [ !Ref Domain, none ] ]
  HasNatKeyName: !Not [ !Equals [ !Ref NatKeyName, none ] ]

Resources:

  BastionStack:
    Type: AWS::CloudFormation::Stack
    Condition: HasBastion
    Properties:
      Parameters:
        AmiId: !Ref BastionAmiId
        InstanceType: !Ref BastionInstanceType
        KeyName: !If [ HasBastionKeyName, !Ref BastionKeyName, !Ref 'AWS::NoValue' ]
        PublicSubnetIdList: !GetAtt VpcSubStack.Outputs.PublicSubnetIdList
        Stage: !Ref Stage
        VpcCidr: !GetAtt VpcSubStack.Outputs.CidrBlock
        VpcId: !GetAtt VpcSubStack.Outputs.VpcId
      TemplateURL: !Sub ${StackUrl}/vpc/bastion.yaml

  PrivateHostedZone:
    Type: AWS::CloudFormation::Stack
    Condition: HasDomain
    Properties:
      Parameters:
        Domain: !Sub internal.${Domain}
        VpcId: !GetAtt VpcSubStack.Outputs.VpcId
      TemplateURL: !Sub ${StackUrl}/vpc/hosted-zone.yaml

  PublicHostedZone:
    Type: AWS::CloudFormation::Stack
    Condition: HasDomain
    Properties:
      Parameters:
        Domain: !Ref Domain
      TemplateURL: !Sub ${StackUrl}/vpc/hosted-zone.yaml

  SubnetANatInstance:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        AmiId: !Ref NatAmiId
        KeyName: !If [ HasNatKeyName, !Ref NatKeyName, !Ref 'AWS::NoValue' ]
        PrivateRouteTableId: !GetAtt VpcSubStack.Outputs.PrivateNatSubnetARouteTable
        PublicSubnetId: !GetAtt VpcSubStack.Outputs.PublicSubnetA
        VpcCidr: !GetAtt VpcSubStack.Outputs.VpcCidr
        VpcId: !GetAtt VpcSubStack.Outputs.VpcId
      TemplateURL: !Sub ${StackUrl}/vpc/nat-instance.yaml

  VpcSubStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        CidrClassB: !Ref CidrClassB
        Name: !Ref Name
        Stage: !Ref Stage
      TemplateURL: !Sub ${StackUrl}/vpc/vpc.yaml

#Outputs:
