AWSTemplateFormatVersion: 2010-09-09
Description: ---

Parameters:

  Domain:
    Type: String

  VpcId:
    Default: none
    Type: AWS::EC2::VPC::Id

Conditions:

  IsPrivate: !Equals [ !Ref VpcId, none ]
  IsPublic: !Not [ !Equals [ !Ref VpcId, none ] ]

Resources:

  PrivateHostedZone:
    Type: 'AWS::Route53::HostedZone'
    Condition: IsPrivate
    Properties:
      HostedZoneConfig:
        Comment: !Sub ${Domain}
      Name: !Ref Domain
      VPCs:
      - VPCId: !Ref VpcId
        VPCRegion: !Ref 'AWS::Region'

  PublicHostedZone:
    Type: 'AWS::Route53::HostedZone'
    Condition: IsPublic
    Properties:
      HostedZoneConfig:
        Comment: !Sub ${Domain}
      Name: !Ref Domain
