#AWSTemplateFormatVersion: 2010-09-09
#Description: ---
#Metadata:

Parameters:

  InstanceType:
    Default: cache.t3.micro
    Type: String

  SubnetIds:
    Type: CommaDelimitedList

  Sequence:
    Default: 1
    Type: String

  VpcId:
    Type: String

#Mappings:

#Conditions:

Resources:

  CacheCluster:
    Type: AWS::ElastiCache::CacheCluster
    Properties:
      AutoMinorVersionUpgrade: true
      AZMode: cross-az
      CacheNodeType: !Ref InstanceType
      CacheParameterGroupName: !Ref ParameterGroup
#      CacheSecurityGroupNames:
#        - String
      CacheSubnetGroupName: !Ref SubnetGroup
      ClusterName: !Sub redis-cluster-${Sequence}
      Engine: redis
      EngineVersion: 5.0.6
#      NotificationTopicArn: String
      NumCacheNodes: 2
#      Port: Integer
#      PreferredAvailabilityZone: String
      PreferredAvailabilityZones:
        - us-east-1a
        - us-east-2a
#      PreferredMaintenanceWindow: String
#      SnapshotArns:
#        - String
#      SnapshotName: String
#      SnapshotRetentionLimit: Integer
#      SnapshotWindow: String
#      Tags:
#        - Tag
      VpcSecurityGroupIds:
        - !GetAtt SecurityGroup.GroupId

  ParameterGroup:
    Type: AWS::ElastiCache::ParameterGroup
    Properties:
      CacheParameterGroupFamily: redis5.0
      Description: Required
#      Properties:
#        Key : Value

  SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: description
      VpcId: !Ref VpcId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 6379
          ToPort: 6379

  SubnetGroup:
    Type: AWS::ElastiCache::SubnetGroup
    Properties:
      CacheSubnetGroupName: redis-cluster-1-group-name
      Description: description
      SubnetIds: !Ref SubnetIds


#Outputs:
